export const FETCH_INTERVIEW_START = 'FETCH_INTERVIEW_START';
export const FETCH_INTERVIEW_SUCCESS = 'FETCH_INTERVIEW_SUCCESS';
export const FETCH_INTERVIEW_ERROR = 'FETCH_INTERVIEW_ERROR';

export const FETCH_INTERVIEWS_START = 'FETCH_INTERVIEWS_START';
export const FETCH_INTERVIEWS_SUCCESS = 'FETCH_INTERVIEWS_SUCCESS';
export const FETCH_INTERVIEWS_ERROR = 'FETCH_INTERVIEWS_ERROR';

export const FETCH_PARTICIPANTS_START = 'FETCH_PARTICIPANTS_START';
export const FETCH_PARTICIPANTS_SUCCESS = 'FETCH_PARTICIPANTS_SUCCESS';
export const FETCH_PARTICIPANTS_ERROR = 'FETCH_PARTICIPANTS_ERROR';